### ISSUE TITLE
Don't log HOOK_SECRET

### ISSUE THREAD

**Issue by sethvargo** [mchmarny/github-activity-counter#3]
https://github.com/mchmarny/github-activity-counter/blob/acd949b09b49a6c1fb039268ef70a1412f2e28b3/main.go#L21 logs the provided secret in plaintext in Stackdriver logs:

<img width="544" alt="Screen Shot 2019-08-12 at 12 17 16 PM" src="https://user-images.githubusercontent.com/408570/62880320-22501e80-bcfb-11e9-8cab-8e46e9779995.png">

(secret has since been rotated)

**Comment by mchmarny** [comment]
Proper fix is to use secrets here but the immediate issue is not fixed by updating the gcputils to latest version.
